### ISSUE TITLE
TaylorF2 reference

### ISSUE THREAD

**Issue by Felipe-4** [tedwards2412/ripple#30]
I am new to GWs so that's probably why I am not finding it, but what is the reference for TaylorF2? In the [LALsuite](https://lscsoft.docs.ligo.org/lalsuite/lalsimulation/group___l_a_l_sim_inspiral_taylor_x_x__c.html) they  reference section III F of [this paper](https://arxiv.org/pdf/0907.0700) which doesn't look like the function implemented here, for one thing the tidal parameters are missing in the formulas of this section.

**Comment by tedwards2412** [comment]
Hi @Felipe-4, unfortunately TaylorF2 has been developed over a number of publications and different versions contain terms up to different PN orders. The paper you linked is a good starting point, but won't contain all the higher order terms (for example the tidal parameters). This notebook https://github.com/tedwards2412/ripple/blob/main/notebooks/check_TaylorF2.ipynb demonstrates that we match with the lalsuite implementation though. Does this help?

**Comment by Felipe-4** [comment]
Ok, Thank you.
