### ISSUE TITLE
PN Coefficients

### ISSUE THREAD

**Issue by Felipe-4** [tedwards2412/ripple#31]
The PN coefficients of IMRPhenomD don't seem to match the ones provided in the arXiv1508.07253, is there a problem with those coefficients?

**Comment by kazewong** [comment]
Is there a specific line(s) of mismatch you found that concerns you? We have benchmarked our implementation with lalsuite extensively, and we found the mismatch between our implementation and lalsuite to be basically at machine precision level https://arxiv.org/pdf/2302.05329

**Comment by tedwards2412** [comment]
No there isn’t a problem. The ripple PhenomD is designed to exactly match the lalsuite version which has slightly different coefficients to what’s in the published table. I’m not exactly sure why it doesn’t match the published version but the codes match and lalsuite has gone through a lot of code review. See the ripple paper for a comparison of the match with lalsuite.

**Comment by Felipe-4** [comment]
I noticed the mismatch starting at 3PN, I just didn't understand why. Thank you for the answers.

**Comment by Felipe-4** [comment]
I noticed the mismatch starting at 3PN, I just didn't understand why. Thank you for the answers.

Edit: I just want to correct myself, there is really no difference between the coefficients, either amplitude or phase. I am attaching a  Mathematica file that I used to check the equivalence
[Ripple.wl.zip](https://github.com/user-attachments/files/16329597/Ripple.wl.zip)
