### ISSUE TITLE
Citing ripple

### ISSUE THREAD

**Issue by hemantaph** [tedwards2412/ripple#33]
In the new update of [gwsnr](https://github.com/hemantaph/gwsnr/tree/main) package, I using `ripple` to call GW waveform. I am submitting a paper draft to JOSS publicationg for the `gwsnr` package. Can you instruct me how to cite `ripple`?

**Comment by ThibeauWouters** [comment]
Hi @hemantaph!

Great to hear that you are using ripple! There is a paper on ripple, you can find the Inspire entry [here](https://inspirehep.net/literature/2631117) and export its bibtex citation there.

I believe this is sufficient and will close the issue with this comment, but do let me know if you prefer to have more information.
