### ISSUE TITLE
IMRPhenomD recompile everytime when input frequnecy changes

### ISSUE THREAD

**Issue by kazewong** [tedwards2412/ripple#4]
`IMRPhenomD.gen_IMRPhenomD_polar` is jitted by default now. This makes jax recompile the code when the length of the input frequency array changes, which introduce massive overhead when trying to deal with dynamic frequency input length such as heterodyne likelihood.

One simple fix is not jitting the functions involved by default, but have the user jit them when needed, which I think should be the desired behavior?

@tedwards2412 @dfm

**Comment by tedwards2412** [comment]
I agree with this. I've removed all the jits from the PhenomD waveform and added a little extra comment on the README to recommend users jit the functions themselves
